/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // 碳智METHAS 品牌色彩系统 - 基于 CSS Variables
        primary: {
          50: 'var(--methas-primary-50)',
          100: 'var(--methas-primary-100)',
          200: 'var(--methas-primary-200)',
          300: 'var(--methas-primary-300)',
          400: 'var(--methas-primary-400)',
          500: 'var(--methas-primary-500)',
          600: 'var(--methas-primary-600)',
          700: 'var(--methas-primary-700)',
          800: 'var(--methas-primary-800)',
          900: 'var(--methas-primary-900)',
          DEFAULT: 'var(--methas-primary-500)',
        },
        // 环保绿色系
        green: {
          50: 'var(--methas-green-50)',
          100: 'var(--methas-green-100)',
          200: 'var(--methas-green-200)',
          300: 'var(--methas-green-300)',
          400: 'var(--methas-green-400)',
          500: 'var(--methas-green-500)',
          600: 'var(--methas-green-600)',
          700: 'var(--methas-green-700)',
          800: 'var(--methas-green-800)',
          900: 'var(--methas-green-900)',
          DEFAULT: 'var(--methas-green-500)',
        },
        // 警示橙色系
        orange: {
          50: 'var(--methas-orange-50)',
          100: 'var(--methas-orange-100)',
          200: 'var(--methas-orange-200)',
          300: 'var(--methas-orange-300)',
          400: 'var(--methas-orange-400)',
          500: 'var(--methas-orange-500)',
          600: 'var(--methas-orange-600)',
          700: 'var(--methas-orange-700)',
          800: 'var(--methas-orange-800)',
          900: 'var(--methas-orange-900)',
          DEFAULT: 'var(--methas-orange-500)',
        },
        // 中性色系统
        gray: {
          50: 'var(--methas-gray-50)',
          100: 'var(--methas-gray-100)',
          200: 'var(--methas-gray-200)',
          300: 'var(--methas-gray-300)',
          400: 'var(--methas-gray-400)',
          500: 'var(--methas-gray-500)',
          600: 'var(--methas-gray-600)',
          700: 'var(--methas-gray-700)',
          800: 'var(--methas-gray-800)',
          900: 'var(--methas-gray-900)',
          DEFAULT: 'var(--methas-gray-500)',
        },
        // 功能色
        success: 'var(--methas-success)',
        warning: 'var(--methas-warning)',
        error: 'var(--methas-error)',
        info: 'var(--methas-info)',
        // 兼容性别名
        secondary: {
          DEFAULT: 'var(--methas-green-500)',
          green: 'var(--methas-green-500)',
        },
        neutral: {
          0: 'var(--methas-gray-50)',
          50: 'var(--methas-gray-50)',
          100: 'var(--methas-gray-100)',
          200: 'var(--methas-gray-200)',
          300: 'var(--methas-gray-300)',
          400: 'var(--methas-gray-400)',
          500: 'var(--methas-gray-500)',
          600: 'var(--methas-gray-600)',
          700: 'var(--methas-gray-700)',
          800: 'var(--methas-gray-800)',
          900: 'var(--methas-gray-900)',
        },
      },
      fontFamily: {
        // 碳智METHAS 字体系统 - 基于 CSS Variables
        primary: 'var(--methas-font-primary)',
        heading: 'var(--methas-font-heading)',
        mono: 'var(--methas-font-mono)',
        // 兼容性别名
        sans: 'var(--methas-font-primary)',
        serif: 'var(--methas-font-heading)',
      },
      fontSize: {
        // 碳智METHAS 响应式字体系统 - 基于 CSS Variables
        'xs': 'var(--methas-text-xs)',
        'sm': 'var(--methas-text-sm)',
        'base': 'var(--methas-text-base)',
        'lg': 'var(--methas-text-lg)',
        'xl': 'var(--methas-text-xl)',
        '2xl': 'var(--methas-text-2xl)',
        '3xl': 'var(--methas-text-3xl)',
        '4xl': 'var(--methas-text-4xl)',
        '5xl': 'var(--methas-text-5xl)',
        // 语义化字体别名
        'body-xs': 'var(--methas-text-xs)',
        'body-sm': 'var(--methas-text-sm)',
        'body-md': 'var(--methas-text-base)',
        'body-lg': 'var(--methas-text-lg)',
        'heading-sm': 'var(--methas-text-lg)',
        'heading-md': 'var(--methas-text-xl)',
        'heading-lg': 'var(--methas-text-2xl)',
        'heading-xl': 'var(--methas-text-3xl)',
        'display-sm': 'var(--methas-text-3xl)',
        'display-md': 'var(--methas-text-4xl)',
        'display-lg': 'var(--methas-text-5xl)',
        'hero-lg': 'var(--methas-text-5xl)',
        'hero-xl': 'var(--methas-text-5xl)',
      },
      fontWeight: {
        light: 'var(--methas-font-light)',
        normal: 'var(--methas-font-normal)',
        medium: 'var(--methas-font-medium)',
        semibold: 'var(--methas-font-semibold)',
        bold: 'var(--methas-font-bold)',
      },
      spacing: {
        // 碳智METHAS 8px 基础间距系统 - 基于 CSS Variables
        '0': 'var(--methas-space-0)',
        '1': 'var(--methas-space-1)',
        '2': 'var(--methas-space-2)',
        '3': 'var(--methas-space-3)',
        '4': 'var(--methas-space-4)',
        '5': 'var(--methas-space-5)',
        '6': 'var(--methas-space-6)',
        '8': 'var(--methas-space-8)',
        '10': 'var(--methas-space-10)',
        '12': 'var(--methas-space-12)',
        '16': 'var(--methas-space-16)',
        '20': 'var(--methas-space-20)',
        '24': 'var(--methas-space-24)',
        '32': 'var(--methas-space-32)',
      },
      borderRadius: {
        'sm': 'var(--methas-radius-sm)',
        'DEFAULT': 'var(--methas-radius-md)',
        'md': 'var(--methas-radius-md)',
        'lg': 'var(--methas-radius-lg)',
        'xl': 'var(--methas-radius-xl)',
        '2xl': 'var(--methas-radius-2xl)',
        'full': 'var(--methas-radius-full)',
      },
      boxShadow: {
        'sm': 'var(--methas-shadow-sm)',
        'md': 'var(--methas-shadow-md)',
        'lg': 'var(--methas-shadow-lg)',
        'xl': 'var(--methas-shadow-xl)',
        '2xl': 'var(--methas-shadow-2xl)',
        'DEFAULT': 'var(--methas-shadow-md)',
      },
      transitionDuration: {
        'fast': 'var(--methas-transition-fast)',
        'normal': 'var(--methas-transition-normal)',
        'slow': 'var(--methas-transition-slow)',
        'DEFAULT': 'var(--methas-transition-normal)',
      },
      transitionTimingFunction: {
        'in-out': 'var(--methas-ease-in-out)',
        'out': 'var(--methas-ease-out)',
        'in': 'var(--methas-ease-in)',
        'DEFAULT': 'var(--methas-ease-out)',
      },
      screens: {
        'sm': 'var(--methas-breakpoint-sm)',
        'md': 'var(--methas-breakpoint-md)',
        'lg': 'var(--methas-breakpoint-lg)',
        'xl': 'var(--methas-breakpoint-xl)',
        '2xl': 'var(--methas-breakpoint-2xl)',
      },
      zIndex: {
        'dropdown': 'var(--methas-z-dropdown)',
        'sticky': 'var(--methas-z-sticky)',
        'fixed': 'var(--methas-z-fixed)',
        'modal-backdrop': 'var(--methas-z-modal-backdrop)',
        'modal': 'var(--methas-z-modal)',
        'popover': 'var(--methas-z-popover)',
        'tooltip': 'var(--methas-z-tooltip)',
        'toast': 'var(--methas-z-toast)',
      },
      maxWidth: {
        '7xl': '1280px',
      },
    },
  },
  plugins: [],
}